version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    working_directory: ~/repo

    steps:

      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run: yarn test
      - run: yarn package
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: yarn publish  --no-git-tag-version --public --new-version 1.1.1-beta.$CIRCLE_SHA1
